name: Daily Scraper Trigger

on:
  schedule:
    - cron: '0 /1 * * *'  # Every day at 4 AM UTC
  workflow_dispatch:

jobs:
  trigger-scrapers:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Scraper Endpoint on Render
        run: |
          curl -X POST https://indian-startup-scraper.onrender.com/api/run-scrapers/
